workflows:
  ios-native-quick-start:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: App156 api key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mon.cs55go0
      vars:
        BUNDLE_ID: "com.mon.cs55go0"
        XCODE_PROJECT: "App156.xcodeproj"
        XCODE_SCHEME: "App156"
        APP_STORE_APPLE_ID: 6462699117
      xcode: latest
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
